### ISSUE TITLE
Tests for 1559 extended requirements 

### ISSUE THREAD

**Issue by holiman** [ethereum/tests#868]
I don't know where to put these, if we want to just place them in the same location as the random-tests, or somehow make a filler for them, so for now I'll just open a ticket and we can see where to go from here. 

These two tests checks the two necessary preconditions for transaction validity in EIP-1559

`1559_MaxFeePerGasExceedsBalance.json`:
```json
{
  "MaxFeePerGasExceedsBalance": {
    "_info": {
      "comment": "This test checks the precondition in 1559: assert sender.balance >= gasLimit * transaction.max_fee_per_gas"
    },
    "env": {
      "currentCoinbase": "b94f5374fce5edbc8e2a8697c15331677e6ebf0b",
      "currentDifficulty": "0x20000",
      "currentGasLimit": "0x26e1f476fe1e22",
      "currentNumber": "0x1",
      "currentTimestamp": "0x3e8",
      "currentBaseFee": "0x100",
      "previousHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "pre": {
      "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
        "code": "0x",
        "storage": {},
        "balance": "0xffffffff",
        "nonce": "0x0"
      },
      "b94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
        "code": "0x",
        "storage": {},
        "balance": "0x0",
        "nonce": "0x1"
      }
    },
    "transaction": {
      "nonce": "0x0",
      "maxFeePerGas": "0x40000",
      "maxPriorityFeePerGas": "0x200",
      "to": "0x0000000000000000000000000000000000000000",
      "data": [
        "0x"
      ],
      "gasLimit": [
        "0x7530"
      ],
      "value": [
        "0x"
      ],
      "secretKey": "0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8"
    },
    "out": "0x",
    "post": {
      "London": [
        {
          "hash": "4adfca7562e66619510a77ea7ea0fb3bef014c9053429fa99a15c8d0132d1789",
          "logs": "1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
          "indexes": {
            "data": 0,
            "gas": 0,
            "value": 0
          }
        }
      ]
    }
  }
}
```
and `1559_MaxPriorityFeePerGasExceedsMaxFeePerGas.json`:
```json
{
  "MaxPriorityFeePerGasExceedsMaxFeePerGas": {
    "_info": {
      "comment": "This test checks the precondition in 1559: assert transaction.max_fee_per_gas >= transaction.max_priority_fee_per_gas"
    },
    "env": {
      "currentCoinbase": "b94f5374fce5edbc8e2a8697c15331677e6ebf0b",
      "currentDifficulty": "0x20000",
      "currentGasLimit": "0x26e1f476fe1e22",
      "currentNumber": "0x1",
      "currentTimestamp": "0x3e8",
      "currentBaseFee": "0x100",
      "previousHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "pre": {
      "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
        "code": "0x",
        "storage": {},
        "balance": "0xffffffff",
        "nonce": "0x0"
      },
      "b94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
        "code": "0x",
        "storage": {},
        "balance": "0x0",
        "nonce": "0x1"
      }
    },
    "transaction": {
      "nonce": "0x0",
      "maxFeePerGas": "0x200",
      "maxPriorityFeePerGas": "0x201",
      "to": "0x0000000000000000000000000000000000000000",
      "data": [
        "0x"
      ],
      "gasLimit": [
        "0x7530"
      ],
      "value": [
        "0x"
      ],
      "secretKey": "0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8"
    },
    "out": "0x",
    "post": {
      "London": [
        {
          "hash": "4adfca7562e66619510a77ea7ea0fb3bef014c9053429fa99a15c8d0132d1789",
          "logs": "1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
          "indexes": {
            "data": 0,
            "gas": 0,
            "value": 0
          }
        }
      ]
    }
  }
}
```

**Comment by qbzzt** [comment]
I agree we need to have tests for these conditions, but I already wrote them.

Filler: https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/ValidBlocks/bcEIP1559/transFailFiller.yml
Filled: https://github.com/ethereum/tests/blob/develop/BlockchainTests/ValidBlocks/bcEIP1559/transFail.json

Account balance check: https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/ValidBlocks/bcEIP1559/transFailFiller.yml#L272-L282

Max priority fee > max fee: https://github.com/ethereum/tests/blob/develop/src/BlockchainTestsFiller/ValidBlocks/bcEIP1559/transFailFiller.yml#L245-L255

**Comment by qbzzt** [comment]
And now we also have state tests, #875

**Comment by qbzzt** [comment]
@holiman , sorry I didn't use your tests, but it was easier for me to just to yml

**Comment by holiman** [comment]
> @holiman , sorry I didn't use your tests, but it was easier for me to just to yml

No worries at all! I just wanted to get the test covered, I don't care if you use my code or something else entirely. Feel free to close this when it's covered

**Comment by holiman** [comment]
Running the first one on `besu`, I get
```
./bins/besu-evm state-test --json  1559_MaxFee.json
picocli.CommandLine$ExecutionException: Error while running command (org.hyperledger.besu.evmtool.StateTestSubCommand@320de594): java.util.NoSuchElementException: No value present
	at picocli.CommandLine.executeUserObject(CommandLine.java:1948)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
	at org.hyperledger.besu.evmtool.EvmToolCommand.parse(EvmToolCommand.java:172)
	at org.hyperledger.besu.evmtool.EvmTool.main(EvmTool.java:30)
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:375)
	at org.hyperledger.besu.ethereum.core.Transaction.lambda$eip1559Preimage$4(Transaction.java:670)
	at org.hyperledger.besu.ethereum.rlp.RLP.encode(RLP.java:107)
	at org.hyperledger.besu.ethereum.core.Transaction.eip1559Preimage(Transaction.java:667)
	at org.hyperledger.besu.ethereum.core.Transaction.computeSenderRecoveryHash(Transaction.java:597)
	at org.hyperledger.besu.ethereum.core.Transaction$Builder.computeSignature(Transaction.java:910)
	at org.hyperledger.besu.ethereum.core.Transaction$Builder.signAndBuild(Transaction.java:902)
	at org.hyperledger.besu.ethereum.referencetests.StateTestVersionedTransaction.get(StateTestVersionedTransaction.java:144)
	at org.hyperledger.besu.ethereum.referencetests.GeneralStateTestCaseSpec.lambda$generate$0(GeneralStateTestCaseSpec.java:65)
	at org.hyperledger.besu.ethereum.referencetests.GeneralStateTestCaseEipSpec.getTransaction(GeneralStateTestCaseEipSpec.java:91)
	at org.hyperledger.besu.evmtool.StateTestSubCommand.traceTestSpecs(StateTestSubCommand.java:169)
	at org.hyperledger.besu.evmtool.StateTestSubCommand.lambda$executeStateTest$0(StateTestSubCommand.java:150)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at org.hyperledger.besu.evmtool.StateTestSubCommand.executeStateTest(StateTestSubCommand.java:150)
	at org.hyperledger.besu.evmtool.StateTestSubCommand.run(StateTestSubCommand.java:137)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)

```
Running it on `nethtest`, I get 
```
./bins/nethtest -i 1559_MaxFee.json 
{"output":"0x","gasUsed":"0x0","time":0}
{"stateRoot":"0x70f6e7b0787279c2ea84178403273ac0bff1d02fd0de398484487a971a77afac"}
[
  {
    "name": "MaxFeePerGasExceedsBalance_d0g0v0_",
    "pass": false,
    "fork": "London"
  }
]

```

cc @RatanRSur @tkstanczak

**Comment by MarekM25** [comment]
@holiman Did you use master branch? The last 1559 checks haven't been merged. We'll do it today I think. I'll check this test https://github.com/ethereum/tests/pull/875 from this PR: https://github.com/NethermindEth/nethermind/pull/3090

**Comment by holiman** [comment]
Edit: _besu_ now matches geth
```
./bins/besu-evm state-test --json  1559_MaxFee.json
{"output":"","gasUsed":"0x7531","time":11695115,"test":"MaxFeePerGasExceedsBalance","fork":"London","d":0,"g":0,"v":0,"postHash":"0x4adfca7562e66619510a77ea7ea0fb3bef014c9053429fa99a15c8d0132d1789","postLogsHash":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","pass":true,"validationError":"transaction up-front cost 7864320000 exceeds transaction sender account balance 4294967295"}
```
```
./bins/evm --json  statetest 1559_MaxFee.json
{"stateRoot": "4adfca7562e66619510a77ea7ea0fb3bef014c9053429fa99a15c8d0132d1789"}
[
  {
    "name": "MaxFeePerGasExceedsBalance",
    "pass": true,
    "fork": "London"
  }
]
```

**Comment by holiman** [comment]
@MarekM25 And nethermind also is in sync with geth: 
```
./bins/nethtest -i 1559_MaxFee.json 
[
  {
    "name": "MaxFeePerGasExceedsBalance_d0g0v0_",
    "pass": true,
    "fork": "London"
  }
]
```
